[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Readings"
pageRef = "readings"
weight = 10

[[main]]
name = "WAREC"
url = "warec"
weight = 10

[[main]]
identifier = "search"
weight = 20
[main.params]
action = "search"
icon = "search"

[[main]]
name = "GitHub"
url = "https://github.com/juliendoutre"
weight = 30
[main.params]
icon = "github"
showName = false
target = "_blank"
