colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
robots = "all"

[header]
layout = "basic"
# logo = "img/logo.jpg"
showTitle = true

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
recentLimit = 5

[article]
showDate = true
showDateUpdated = true
showAuthor = false
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
# editURL = "https://github.com/username/repo/"
editAppendPath = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showWordCount = false
showComments = true
# sharingLinks = ["facebook", "twitter", "mastodon", "pinterest", "reddit", "linkedin", "email"]

[list]
showBreadcrumbs = true
showSummary = true
showTableOfContents = true
showTaxonomies = true
groupByYear = true
paginationWidth = 1

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
