name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout dependencies
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2.
        with:
          submodules: true
          fetch-depth: 0
      - name: install hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.145.0'
      - name: build static assets
        run: hugo --minify
      - name: release static assets
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
